import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import "./theme-config.css";
import ThemeSwitcher from "./ThemeSwitcher";
import ReduxProvider from "./components/ReduxProvider";
import ToastContainers from "./components/ToastContainers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const quicksand = Quicksand({
  variable: "--font-quick-sand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <ReduxProvider>
          <ThemeSwitcher>
            <Navbar />
            <main className="p-5 ">{children}</main>
          </ThemeSwitcher>
        </ReduxProvider>
        <ToastContainers />
      </body>
    </html>
  );
}
